import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer';
import { Background2 } from '@/ui/Backgrounds'
import '../globals.css'
import { Outfit } from 'next/font/google'
import { cn } from '@/lib/utils';
import Providers from '@/components/Providers';

const outfit = Outfit({ subsets: ['latin'], variable: '--font-outfit' })

export const metadata = {
  title: 'Dipzin | Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn('subpixel-antialiased font-sans', outfit.variable)}>
      <body className={cn('bg-fixed bg-gradient-to-tr from-slate-200 to-slate-300 dark:from-slate-950 dark:to-slate-950 min-h-screen w-full h-screen overflow-x-clip')}>
        <Providers>
          <Navbar />
          <main className='pt-24 max-w-full mx-10'>
            {children}
          </main>
          {/* <Footer /> */}
          <Background2 />
        </Providers>
      </body>
    </html>
  )
}
