import Navbar from '@/components/Navbar'
import Background from '@/ui/Background'
import './globals.css'
import GlobalProvider from "../lib/globalContext";
import { Poppins } from 'next/font/google'
import { cn } from '@/lib/utils';

const poppins = Poppins({
  subsets: ["latin"],
  display: 'swap',
  weight: ["100", "300", "500", "700", "900"],
  variable: '--font-poppins',
  fallback: ['Poppins']
});

export const metadata = {
  title: 'Dipzin | Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn('subpixel-antialiased font-sans', poppins.variable)}>
      <body className={cn('bg-gradient-to-tr from-[#0D1018] to-[#09132E] min-h-screen w-full h-full')}>
        <GlobalProvider>
          <Navbar />
          <main className='pt-24 max-w-full mx-10'>
            {children}
          </main>
          <Background />
        </GlobalProvider>
      </body>
    </html>
  )
}
