import '@/styles/global.css';

import { Background } from '@/components/UI/background';
import { Toaster } from '@/components/Shared/toaster';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Background />
        <Toaster />
      </body>
    </html>
  );
}
