import '@/styles/global.css';

import { Toaster } from '@/components/Shared/toaster';
import { SessionProvider } from 'next-auth/react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-poppins bg-slate-950">
        <SessionProvider>
          {children}
        </SessionProvider>
        {/* <Background /> */}
        <Toaster />
      </body>
    </html>
  );
}
