import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer';
import { Background1 } from '@/ui/Backgrounds'
import '../globals.css'
import { Outfit } from 'next/font/google'
import { cn } from '@/lib/utils';
import Providers from '@/components/Providers';
import Banner from '@/components/Banner';
import HomeNavigator from '@/components/HomeNavigator';
import MainNavigator from '@/components/navigator/main/main';

const outfit = Outfit({ subsets: ['latin'], variable: '--font-outfit' })

export const metadata = {
  title: 'Dipzin | Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn('subpixel-antialiased font-sans', outfit.variable)}>
      <body className={cn('bg-fixed bg-gradient-to-tr from-slate-200 to-slate-300 dark:from-slate-950 dark:to-slate-950 min-h-screen w-full h-screen')}>
        <Providers>
          <Navbar />
          <main className='pt-24 max-w-[82%]  mx-auto'>
            <Banner />
            <HomeNavigator />
            {children}
            <MainNavigator />
          </main>
          <Footer />
          <Background1 />
        </Providers>
      </body>
    </html>
  )
}
