apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "2"
    io.portainer.kubernetes.application.note: ""
  generation: 2
  labels:
    io.portainer.kubernetes.application.name: dipzin-git-nextjs
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: dipzin
  name: dipzin-git-nextjs
  namespace: dipzin
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dipzin-git-nextjs
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dipzin-git-nextjs
        io.portainer.kubernetes.application.name: dipzin-git-nextjs
    spec:
      containers:
        - image: ghcr.io/dabbonet/dipzin-nextjs:latest
          imagePullPolicy: IfNotPresent
          name: dipzin-git-nextjs
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: registry-1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.portainer.kubernetes.application.name: dipzin-git-nextjs
    io.portainer.kubernetes.application.owner: admin
    io.portainer.kubernetes.application.stack: dipzin
  name: dipzin-git-nextjs
  namespace: dipzin
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: port-0
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: dipzin-git-nextjs
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
