apiVersion: apps/v1
kind: Deployment
metadata:
  name: dipzin-git-deployment
  namespace: dipzin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dipzin-nextjs
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dipzin-nextjs
    spec:
      containers:
      - name: dipzin-nextjs
        image: ghcr.io/dabbonet/dipzin-nextjs:latest
        ports:
        - containerPort: 3000
          protocol: TCP
      imagePullSecrets:
        - name: registry-1
      serviceAccountName: dipzin-nextjs-service
      dnsPolicy: ClusterFirst
      restartPolicy: Always


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: dipzin-nextjs
  name: dipzin-nextjs
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: dipzin-nextjs
  sessionAffinity: None
  type: NodePort